name: Deploy to GitHub Pages Docs

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run docs:build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: ./docs/.vitepress/dist
